### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by MMhaidari** [sumon766/leaderboard#3]
# Highlights
1.  repo is documented well 🔥 

## what should be considered 
- [ ] kindly  change the type of score input to only number as it is accepting types as well
- [ ] kindly remove the commented code in the HML file as it makes the code look unprofessional 
- [ ] kindly make the score list dynamic

### optional suggestion
- kindly add mobile support as well to make it available for mobile users as well

**Comment by sumon766** [comment]
@MMhaidari Thank you for your suggestions, I will definitely make changes according to your advice.
